# -*- coding: utf-8 -*-
"""Copy of magic_formula.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VkYmSlRuSVPFkbjX2eFJMAJA_f4Cscbu

OBS: O código a seguir é apenas um protótipo.
"""

# Step 1A: install core + helpers
import os, glob, json, numpy as np, pandas as pd
from pathlib import Path
# -*- coding: utf-8 -*-
# Keep EVERYTHING from the TTC Run files; add canonical duplicates for convenience.

import os, glob, numpy as np, pandas as pd
from pathlib import Path

import master_builder as mb

import matplotlib.pyplot as plt
from dataclasses import dataclass, asdict
from typing import Dict
import numpy as np

# === change this to your folder ===
FOLDER = "/content/drive/MyDrive/TTC/Data"
OUT_MASTER = os.path.join(FOLDER, "master_all.csv")
OUT_PARAMS_FY = os.path.join(FOLDER, "fitted_params_fy.json")
OUT_PARAMS_FX = os.path.join(FOLDER, "fitted_params_fx.json")

# MAGIC FORMULA FY
# Pack/unpack helpers
param_names = ["pDy1","pDy2","pDy3","pDy4","pCy1","pKy1","pKy2","pKy3",
               "pEy1","pEy2","pEy3","pEy4","pHy1","pHy2","pVy1","pVy2"]

@dataclass
class LateralParams:
    FZ0: float = 1500.0
    # Peak (D) load & camber dependence
    pDy1: float = 1.0
    pDy2: float = 0.0
    pDy3: float = 0.0
    pDy4: float = 0.0  # camber sensitivity on D (abs(γ))
    # Shape factor
    pCy1: float = 1.35
    # Stiffness (Ky) baseline and dependencies -> used to compute B
    pKy1: float = 18.0
    pKy2: float = 0.0
    pKy3: float = 0.0
    # Curvature (E) dependencies
    pEy1: float = -1.6
    pEy2: float = 0.0
    pEy3: float = 0.0
    pEy4: float = 0.0
    # Horizontal/vertical shifts
    pHy1: float = 0.0
    pHy2: float = 0.0
    pVy1: float = 0.0
    pVy2: float = 0.0

@dataclass
class LongitudinalParams:
    FZ0: float = 1500.0 # Same reference load as Fy
    # Peak (D) load & camber dependence
    pDx1: float = 1.0   # Peak friction coefficient Fx at Fz0
    pDx2: float = 0.0   # Variation of Fx peak friction with load
    pDx3: float = 0.0   # Variation of Fx peak friction with squared camber (often small/zero)
    # Shape factor
    pCx1: float = 1.65  # Shape factor Fx
    # Stiffness (K) baseline and dependencies -> used to compute B
    pKx1: float = 20.0  # Longitudinal slip stiffness Kx/Fz at Fz0
    pKx2: float = 0.0   # Variation of slip stiffness Kx/Fz with load
    pKx3: float = 0.0   # Exponent in slip stiffness Kx/Fz with load
    # Curvature (E) dependencies
    pEx1: float = 0.0   # Longitudinal curvature Efx at Fznom
    pEx2: float = 0.0   # Variation of curvature Efx with load
    pEx3: float = 0.0   # Variation of curvature Efx with load squared
    pEx4: float = 0.0   # Factor in curvature Efx while driving/braking (sign(kappa))
    # Horizontal/vertical shifts
    pHx1: float = 0.0   # Horizontal shift Shx at Fznom
    pHx2: float = 0.0   # Variation of shift Shx with load
    pVx1: float = 0.0   # Vertical shift Svx/Fz at Fznom
    pVx2: float = 0.0   # Variation of shift Svx/Fz with load


# Keep only rows with the columns we need

def getPureLateral(data):

    needFy = ["SA","FY","FZ","IA","KAPPA","test_type","run_id","FZ_set","IA_set","V","P","TIRE_TEMP"]
    for c in needFy:
        if c not in data.columns: data[c] = np.nan

    # Use pure lateral runs (and κ≈0 as a safety net)
    lat = data[data["test_type"].isin(["lateral_pure","combined"])].copy()
    lat = lat[np.isfinite(lat["SA"]) & np.isfinite(lat["FY"]) & np.isfinite(lat["FZ"]) & np.isfinite(lat["IA"])]
    lat = lat[np.abs(lat["KAPPA"].fillna(0.0)) < 0.01]  # ~1% slip ≈ pure lateral
    return lat

def getReferenceFz(lat):
    FZ0 = float(np.nanmedian(lat["FZ_set"].dropna())) if lat["FZ_set"].notna().any() else float(np.nanmedian(lat["FZ"]))
    return FZ0




def mf_shape(x, B, C, D, E, SH=0.0, SV=0.0):
    xs = x + SH
    return D * np.sin(C * np.arctan(B*xs - E*(B*xs - np.arctan(B*xs)))) + SV

def fy_pure(alpha, FZ, gamma, p: LateralParams):
    z = (FZ - p.FZ0) / p.FZ0
    C = p.pCy1
    D = (p.pDy1 + p.pDy2*z + p.pDy3*z*z) * FZ * (1 - p.pDy4*np.abs(gamma))
    SH = p.pHy1 + p.pHy2*z
    SV = (p.pVy1 + p.pVy2*z) * FZ
    Ky = (p.pKy1 * (1 + p.pKy2*z) * (1 - p.pKy3*np.abs(gamma))) * p.FZ0
    B = Ky / (C * (np.abs(D) + 1e-9))
    E = p.pEy1 + p.pEy2*z + p.pEy3*gamma + p.pEy4*gamma*z

    return mf_shape(alpha, B, C, D, E, SH, SV)

def save_params_to_json(params_dataclass, path):
    """Saves a parameter dataclass to a JSON file."""
    print(f"Saving parameters to {path}...")
    try:
        with open(path, 'w') as f:
            json.dump(asdict(params_dataclass), f, indent=4)
        print("Save complete.")
    except Exception as e:
        print(f"Error saving parameters: {e}")

def load_params_from_json(ParamsClass, path, FZ0):
    """Loads parameters from JSON and returns the specific dataclass."""
    print(f"Loading parameters from {path}...")
    try:
        with open(path, 'r') as f:
            data = json.load(f)
        # Ensure FZ0 from the *current data* is used, overriding the saved one
        data['FZ0'] = FZ0
        return ParamsClass(**data)
    except Exception as e:
        print(f"Error loading parameters: {e}")
        return None

def small_angle_stiffness(alpha, Fy, max_abs_alpha=np.deg2rad(1.5)):
    m = np.abs(alpha) < max_abs_alpha
    if m.sum() < 8:
        return np.nan
    # simple least-squares slope through origin
    a = alpha[m]; y = Fy[m]
    return float(np.dot(a, y) / (np.dot(a, a) + 1e-12))

def guess_params(lat_df, FZ0):
    # bucket by run (or by FZ_set, IA_set) to sample across conditions
    groups = lat_df.groupby("run_id")
    K_list, D_list, z_list, g_list = [], [], [], []
    for _, g in groups:
        if len(g) < 200:
            continue
        a = g["SA"].to_numpy()
        fy = g["FY"].to_numpy()
        FZ = float(np.nanmedian(g["FZ"]))
        IA = float(np.nanmedian(g["IA"]))
        K = small_angle_stiffness(a, fy)
        if not np.isfinite(K):
            continue
        D = float(np.nanmax(np.abs(fy)))
        if D < 100:
            continue
        K_list.append(K); D_list.append(D); z_list.append((FZ - FZ0)/FZ0); g_list.append(IA)
    # Robust medians
    Ky0 = np.nanmedian(K_list) / (FZ0 + 1e-9)
    Dy1 = np.nanmedian([D/(FZ0+1e-9) for D in D_list])
    p0 = LateralParams(
        FZ0=FZ0,
        pDy1 = max(0.6, min(1.5, Dy1)),
        pCy1 = 1.25,
        pKy1 = max(8.0, min(30.0, Ky0*FZ0)),
        pEy1 = -1.6,
        pHy1 = 0.0, pVy1 = 0.0
    )
    return p0

from scipy.optimize import least_squares


def p_to_vec(p: LateralParams):
    return np.array([getattr(p, k) for k in param_names], dtype=float)

def vec_to_p(v, FZ0):
    kwargs = dict(zip(param_names, v))
    kwargs["FZ0"] = FZ0
    return LateralParams(**kwargs)

# Build data arrays

def buildDataArrays(lat, dataArray):
    dataArray["A"]= lat["SA"].to_numpy()
    dataArray["FZ"] = lat["FZ"].to_numpy()
    dataArray["GA"] = lat["IA"].to_numpy()
    dataArray["FY"] = lat["FY"].to_numpy()
    dataArray["A_rad"] = np.deg2rad(dataArray["A"])
    dataArray["GA_rad"] = np.deg2rad(dataArray["GA"])
    return dataArray



# Weights: more weight at small |α| and near peak |FY|
def getFyWeights(dataArray):
    w_small = 1.0 / (1.0 + (dataArray["A"]/np.deg2rad(2.0))**2)
    peak = np.maximum(0.0, np.abs(dataArray["FY"])/np.nanmax(np.abs(dataArray["FY"])))
    W = 0.6*w_small + 0.4*peak
    weights = {"w_small": w_small, "W": W}
    return weights

def residuals(theta, FZ0, dataArray, weights):
    p = vec_to_p(theta, FZ0)
    pred = fy_pure(dataArray["A_rad"], dataArray["FZ"], dataArray["GA_rad"], p)
    return (pred - dataArray["FY"]) * weights["W"]

# Bounds (loose but sane)
# --- FY PARAMETER FITTING (with Caching) ---

def fyFitting(p0, FZ0):
    print("Starting Stage 1: Fitting shape parameters...")
    lo_stage1 = np.array([ 0.2, -2.0, -2.0,  0.0, 0.8,  2.0, -2.0,  0.0,
                          -2.5, -1.0, -1.0, -1.0,-0.05,-0.05,-0.05,-0.05])
    hi_stage1 = np.array([ 2.5,  2.0,  2.0,  1.0, 2.0, 40.0,  2.0,  1.0,
                           0.0,  1.0,  1.0,  1.0, 0.05, 0.05, 0.05, 0.05])
    theta0_stage1 = p_to_vec(p0) # p0 comes from guess_params()
    res_stage1 = least_squares(residuals, theta0_stage1, bounds=(lo_stage1, hi_stage1),
                             loss="soft_l1", f_scale=0.5, max_nfev=20000, verbose=1)

    print("\nStage 1 complete. Now starting Stage 2 to correct offset...")

    # --- STAGE 2: Find the OFFSET (fast, with wide bounds) ---
    lo_stage2 = np.array([ 0.2, -2.0, -2.0,  0.0, 0.8,  2.0, -2.0,  0.0,
                          -2.5, -1.0, -1.0, -1.0,-0.3,-0.3,-0.3,-0.3])
    hi_stage2 = np.array([ 2.5,  2.0,  2.0,  1.0, 2.0, 40.0,  2.0,  1.0,
                           0.0,  1.0,  1.0,  1.0, 0.3, 0.3, 0.3, 0.3])
    theta0_stage2 = res_stage1.x
    res_stage2 = least_squares(residuals, theta0_stage2, bounds=(lo_stage2, hi_stage2),
                             loss="soft_l1", f_scale=0.5, max_nfev=20000, verbose=1)

    # Your final, correct parameters are the result of Stage 2
    plat = vec_to_p(res_stage2.x, FZ0)
    print("\nStage 2 complete. Final parameters found.")
    return plat

"""




if os.path.exists(OUT_PARAMS_FY):
    # File exists, load it
    plat = load_params_from_json(LateralParams, OUT_PARAMS_FY, FZ0)
    if plat is None:
        print("Failed to load params, re-fitting...")
        # Set a flag or re-run fitting here if loading fails
        # For simplicity, we'll just stop (or you can force-fit)
        raise ValueError("Parameter file corrupted. Delete it and re-run.")
else:
    # File does not exist, run the full fitting process
    print(f"No parameter file found at {OUT_PARAMS_FY}. Running new Fy fit...")

    # --- STAGE 1: Find the SHAPE (fast, with tight bounds) ---
    

    # Save the newly fitted parameters
    save_params_to_json(plat, OUT_PARAMS_FY)

# This print and the plotting code remain outside the if/else
print("\n--- Final FY Parameters (Loaded or Fitted) ---")
print(plat)
"""

import matplotlib.pyplot as plt

def overlay_plot(lat, plat, fz_target, ia_target, tol_fz=75, tol_ia=0.25):
    sl = lat[(np.abs(lat["FZ_set"]-fz_target)<tol_fz) & (np.abs(lat["IA_set"]-ia_target)<tol_ia)].copy()
    if sl.empty:
        print("No slice for FZ≈",fz_target," IA≈",ia_target);
        return
    a = sl["SA"].to_numpy()
    y = sl["FY"].to_numpy()
    fz = sl["FZ"].to_numpy()
    ia = sl["IA"].to_numpy()
    a_grid = np.linspace(np.min(a), np.max(a), 200)
    # use slice medians for model line
    fz_m = float(np.nanmedian(fz)); ia_m = float(np.nanmedian(ia))

    a_grid_rad = np.deg2rad(a_grid)
    ia_m_rad = np.deg2rad(ia_m)


    yhat = fy_pure(a_grid_rad, fz_m, ia_m_rad, plat)
    plt.figure()
    plt.scatter(a, y, s=6, alpha=0.5, color='c', label="data")
    plt.plot(a_grid, yhat, lw=2, color='red', label=f"MF fit @ FZ={fz_m:.0f}N, IA={ia_m:.2f}°")
    plt.axhline(0,color='k',lw=0.5); plt.axvline(0,color='k',lw=0.5)
    plt.xlabel("Slip angle α [deg]"); plt.ylabel("FY [N]"); plt.legend(); plt.grid(True); plt.show()

#Igor: n sei o que o bloco abaixo faz

"""


# Try a couple of slices (adjust to loads you actually have)
loads = np.nanpercentile(lat["FZ_set"].dropna(), [20, 50, 80])
camber = np.nanmedian(lat["IA_set"].dropna()) if lat["IA_set"].notna().any() else 0.0
for fz_t in loads:
    overlay_plot(lat, plat, fz_t, camber)

import numpy as np
from dataclasses import dataclass


"""

def fx_pure(kappa, FZ, gamma, p: LongitudinalParams):
    """Calculates pure longitudinal force (Fx) using Magic Formula."""
    z = (FZ - p.FZ0) / p.FZ0
    C = p.pCx1 # [Shape factor Cfx]
    # [Peak longitudinal friction coefficient Mux]
    mu_x = (p.pDx1 + p.pDx2 * z) * (1 - p.pDx3 * gamma**2)
    D = mu_x * FZ # [Peak factor Dfx = mux * Fz]
    # [Horizontal shift Shx]
    SH = p.pHx1 + p.pHx2 * z
    # [Vertical shift Svx]
    SV = (p.pVx1 + p.pVx2 * z) * FZ
    # [Longitudinal slip stiffness Kx = Bx*Cx*Dx]
    Kx = FZ * (p.pKx1 + p.pKx2 * z) * np.exp(p.pKx3 * z)
    # [Stiffness factor Bfx = Kx / (Cx*Dx)]
    B = Kx / (C * (np.abs(D) + 1e-9)) # Add epsilon to avoid division by zero
    # [Curvature factor Efx]
    E = (p.pEx1 + p.pEx2 * z + p.pEx3 * z**2) * (1 - p.pEx4 * np.sign(kappa + SH))

    # Clamp E to recommended range <= 1
    E = np.minimum(E, 1.0)

    return mf_shape(kappa, B, C, D, E, SH, SV)

# Assuming 'df' is your master DataFrame loaded earlier
# Keep only rows with the necessary columns
#pq n precisa da precao?
need_fx = ["KAPPA", "FX", "FZ", "IA", "SA", "test_type", "run_id", "FZ_set", "IA_set"]

def getPureLongitudinal(data):
    for c in need_fx:
        if c not in data.columns: data[c] = np.nan

    # Use pure longitudinal runs (and SA ≈ 0 as a safety net)
    lon = data[data["test_type"].isin(["longitudinal_pure", "combined"])].copy()
    lon = lon[np.isfinite(lon["KAPPA"]) & np.isfinite(lon["FX"]) & np.isfinite(lon["FZ"]) & np.isfinite(lon["IA"])]
    # Allow slightly larger SA deviation than KAPPA for Fy fitting, e.g., ~1 degree
    lon = lon[np.abs(np.deg2rad(lon["SA"].fillna(0.0))) < np.deg2rad(1.0)]

    print("Longitudinal rows:", len(lon), " unique runs:", lon["run_id"].nunique())
    return lon

def small_slip_stiffness_lon(kappa, Fx, max_abs_kappa=0.03):
    """Calculate longitudinal stiffness CFk = dFx/dkappa at kappa=0."""
    m = np.abs(kappa) < max_abs_kappa
    if m.sum() < 8:
        return np.nan
    # simple least-squares slope through origin
    k = kappa[m]; f = Fx[m]
    return float(np.dot(k, f) / (np.dot(k, k) + 1e-12))

def guess_params_fx(lon_df, FZ0):
    """Guess initial parameters for Fx Magic Formula."""
    groups = lon_df.groupby("run_id")
    K_list, D_list, z_list = [], [], []
    for _, g in groups:
        if len(g) < 200: continue # Need enough points per run
        k = g["KAPPA"].to_numpy()
        fx = g["FX"].to_numpy()
        FZ = float(np.nanmedian(g["FZ"]))
        IA = float(np.nanmedian(g["IA"]))
        K = small_slip_stiffness_lon(k, fx)
        if not np.isfinite(K): continue
        D = float(np.nanmax(np.abs(fx)))
        if D < 100: continue
        K_list.append(K); D_list.append(D); z_list.append((FZ - FZ0)/FZ0)

    # Robust medians, normalized where appropriate
    Kx0_norm = np.nanmedian([K/(FZ+1e-9) for K, FZ in zip(K_list, [z*FZ0+FZ0 for z in z_list])])
    Dx1 = np.nanmedian([D/(FZ0+1e-9) for D in D_list])

    # Initial guess structure
    p0_fx = LongitudinalParams(
        FZ0=FZ0,
        pDx1 = max(0.6, min(2.0, Dx1)), # Peak friction
        pCx1 = 1.65,                    # Typical shape
        pKx1 = max(10.0, min(30.0, Kx0_norm)), # Stiffness / Fz
        pEx1 = 0.0,                     # Start with no curvature asymmetry
        pHx1 = 0.0, pVx1 = 0.0          # Start with no shifts
    )
    # Basic load dependencies (can be refined in fitting)
    if len(z_list) > 5: # Need variation in load to estimate
        try:
             # Very rough linear fit for stiffness vs load (z)
            K_norm_list = [K/(FZ+1e-9) for K, FZ in zip(K_list, [z*FZ0+FZ0 for z in z_list])]
            fit_K = np.polyfit(z_list, K_norm_list, 1)
            p0_fx.pKx1 = max(10.0, min(30.0, fit_K[1])) # Intercept is pKx1
            p0_fx.pKx2 = max(-10.0, min(10.0, fit_K[0] / (p0_fx.pKx1 + 1e-9))) # Slope relates to pKx2

            # Very rough linear fit for peak friction vs load (z)
            D_norm_list = [D/(FZ+1e-9) for D, FZ in zip(D_list, [z*FZ0+FZ0 for z in z_list])]
            fit_D = np.polyfit(z_list, D_norm_list, 1)
            p0_fx.pDx1 = max(0.6, min(2.0, fit_D[1])) # Intercept is pDx1
            p0_fx.pDx2 = max(-1.0, min(1.0, fit_D[0] / (p0_fx.pDx1 + 1e-9))) # Slope relates to pDx2
        except Exception as e:
            print(f"Warning during load dependency guessing: {e}")

    return p0_fx

from scipy.optimize import least_squares

# Pack/unpack helpers for Fx
param_names_fx = ["pDx1","pDx2","pDx3","pCx1","pKx1","pKx2","pKx3",
                  "pEx1","pEx2","pEx3","pEx4","pHx1","pHx2","pVx1","pVx2"]

def p_fx_to_vec(p: LongitudinalParams):
    return np.array([getattr(p, k) for k in param_names_fx], dtype=float)

def vec_to_p_fx(v, FZ0):
    kwargs = dict(zip(param_names_fx, v))
    kwargs["FZ0"] = FZ0
    return LongitudinalParams(**kwargs)

def buildDataArrayFx(lon):
    # Build data arrays for Fx fitting
    dataArray={}
    dataArray["K"]= lon["KAPPA"].to_numpy()
    dataArray["FX"] = lon["FX"].to_numpy()
    dataArray["FZ"] = lon["FZ"].to_numpy()
    dataArray["GA"] = lon["IA"].to_numpy() # Camber angle
    dataArray["GA_rad"] = np.deg2rad(dataArray["GA"])
    return dataArray

def getFxWeights(dataArray):
# Weights: similar to Fy, emphasize small slip and peak region
    w_small_k = 1.0 / (1.0 + (dataArray["K"]/0.05)**2) # Emphasize +/- 5% slip
    peak_k = np.maximum(0.0, np.abs(dataArray["FX"])/np.nanmax(np.abs(dataArray["FX"])))
    W_fx = 0.6*w_small_k + 0.4*peak_k
    weights = {"w_small": w_small_k, "W": W_fx}
    return weights

# Residuals function for Fx
def residuals_fx(theta, FZ0, dataArray, weights):
    p = vec_to_p_fx(theta, FZ0)
    pred = fx_pure(dataArray["K"], dataArray["FZ"], dataArray["GA_rad"], p)
    resid = (pred - dataArray["FX"]) * weights["W"]
    # Penalize negative stiffness at origin slightly
    Kx0 = dataArray["FZ"] * (p.pKx1 + p.pKx2 * ((dataArray["FZ"]-p.FZ0)/p.FZ0)) * np.exp(p.pKx3 * ((dataArray["FZ"]-p.FZ0)/p.FZ0))
    stiffness_penalty = np.mean(np.maximum(0, -Kx0)) * 10
    return np.append(resid, stiffness_penalty)


# Bounds (adjust based on expectations for the specific tire)
# --- FX PARAMETER FITTING (with Caching) ---
"""


if os.path.exists(OUT_PARAMS_FX):
    # File exists, load it
    plon = load_params_from_json(LongitudinalParams, OUT_PARAMS_FX, FZ0)
    if plon is None:
        raise ValueError("Parameter file corrupted. Delete it and re-run.")
else:
    # File does not exist, run the full fitting process
    print(f"No parameter file found at {OUT_PARAMS_FX}. Running new Fx fit...")

"""
def fxFitting(lon, FZ0):
    # Get initial guess
    p0_fx = guess_params_fx(lon, FZ0)
    theta0_fx = p_fx_to_vec(p0_fx)

    # Bounds (adjust based on expectations for the specific tire)
    lo_fx = np.array([ 0.2, -1.0, -1.0,  1.0,  5.0, -15.0, -2.0, # pDx1-3, pCx1, pKx1-3
                      -2.0, -2.0, -2.0, -1.0, -0.1, -0.1, -0.1, -0.1]) # pEx1-4, pHx1-2, pVx1-2
    hi_fx = np.array([ 2.5,  1.0,  1.0,  2.0, 40.0,  15.0,  2.0, # pDx1-3, pCx1, pKx1-3
                       1.0,  2.0,  2.0,  1.0,  0.1,  0.1,  0.1,  0.1]) # pEx1-4, pHx1-2, pVx1-2

    # Run optimization
    print("Starting Fx parameter fitting...")
    res_fx = least_squares(residuals_fx, theta0_fx, bounds=(lo_fx, hi_fx),
                           loss="soft_l1", f_scale=0.5, max_nfev=20000, verbose=2)

    plon = vec_to_p_fx(res_fx.x, FZ0)
    return plon
"""


    print("\nFx Fitting complete. Final parameters:")

    # Save the newly fitted parameters
    save_params_to_json(plon, OUT_PARAMS_FX)

# This print and the plotting code remain outside the if/else
print("\n--- Final FX Parameters (Loaded or Fitted) ---")
print(plon)
"""

# ... your plotting code for Fx ...


def overlay_plot_fx(lon, plon, fz_target, ia_target, tol_fz=75, tol_ia=0.25):
    """Plots Fx vs Kappa data slice and MF fit."""
    sl = lon[(np.abs(lon["FZ_set"] - fz_target) < tol_fz) & (np.abs(lon["IA_set"] - ia_target) < tol_ia)].copy()
    if sl.empty:
        print(f"No slice for FZ ≈ {fz_target:.0f}, IA ≈ {ia_target:.2f}")
        return

    k = sl["KAPPA"].to_numpy()
    fx = sl["FX"].to_numpy()
    fz_sl = sl["FZ"].to_numpy() # Use actual FZ from slice for median calc
    ia_sl = sl["IA"].to_numpy() # Use actual IA from slice for median calc

    k_grid = np.linspace(np.min(k), np.max(k), 200)
    # Use slice medians for model line
    fz_m = float(np.nanmedian(fz_sl))
    ia_m = float(np.nanmedian(ia_sl))
    ia_m_rad = np.deg2rad(ia_m)

    fx_hat = fx_pure(k_grid, fz_m, ia_m_rad, plon)

    plt.figure(figsize=(8, 5))
    plt.scatter(k * 100, fx, s=8, alpha=0.6, color='c', label=f"Data (FZ≈{fz_target:.0f}N, IA≈{ia_target:.1f}°)")
    plt.plot(k_grid * 100, fx_hat, lw=2.5, color='red', label=f"MF fit @ FZ={fz_m:.0f}N, IA={ia_m:.1f}°")
    plt.axhline(0, color='k', lw=0.7)
    plt.axvline(0, color='k', lw=0.7)
    plt.xlabel("Longitudinal Slip κ [%]")
    plt.ylabel("Longitudinal Force Fx [N]")
    plt.title(f"Fx vs Kappa Fit (Target: FZ={fz_target:.0f}N, IA={ia_target:.1f}°)")
    plt.legend()
    plt.grid(True, linestyle=':')
    plt.ylim(bottom=min(0, np.min(fx)-200), top=max(0, np.max(fx)+200)) # Adjust ylim dynamically
    plt.xlim(left=min(0,np.min(k)*100-5), right=max(0, np.max(k)*100+5))
    plt.show()
"""

# Try plotting a couple of slices (adjust targets to your data)
loads_lon = np.nanpercentile(lon["FZ_set"].dropna(), [20, 50, 80]) if lon["FZ_set"].notna().any() else [FZ0]
camber_lon = np.nanmedian(lon["IA_set"].dropna()) if lon["IA_set"].notna().any() else 0.0

print("\n--- Plotting Fx Results ---")
for fz_t in loads_lon:
    overlay_plot_fx(lon, plon, fz_t, camber_lon)
"""