# -*- coding: utf-8 -*-
"""Copy of magic_formula.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mEWXi_bEyRNbkoloPaXyes_fh0fnJv4h

OBS: O código a seguir é apenas um protótipo. A versão final deverá rodar localmente

Ver. 0.3

"""

import os, glob, numpy as np, pandas as pd
from pathlib import Path

fzTestValues = [-222, -445, -667, -890, -1112]
inclinationAngleTestValues = [0,2,4]
pressureTestValues = [55, 69, 83, 97]
velocityTestValues = [24, 40, 72]

def updateSmallestError(value, error, smallestErrorValue, smallestError):
    if error < smallestError:
            smallestError = error
            smallestErrorValue = value
    return smallestErrorValue, smallestError


def snapToValues(value, options):
    snapedValue = options[0]
    smallestError = abs(options[0] - value)
    for option in options:
        error = abs(option - value)
        snapedValue, smallestError = updateSmallestError(option, error, snapedValue, smallestError)
        
    return snapedValue

#Gemini
def clamp_to_nearest(df, col_name, allowed_vals):
    # Ensure allowed_vals is a sorted numpy array
    allowed = np.sort(np.array(list(allowed_vals)))
    
    # Get the raw values from the column
    data = df[col_name].values
    
    # Find where data would be inserted (indices)
    idx = np.searchsorted(allowed, data, side='left')
    
    # Prevent out-of-bounds indices
    # (idx 0 stays 0, idx len(allowed) becomes len(allowed)-1)
    idx_right = np.clip(idx, 0, len(allowed) - 1)
    idx_left = np.clip(idx - 1, 0, len(allowed) - 1)
    
    # Use np.take to safely grab the actual values from the target set
    val_right = np.take(allowed, idx_right)
    val_left = np.take(allowed, idx_left)
    
    # Calculate which one is closer for each row
    # np.abs handles the entire array at once
    dist_left = np.abs(data - val_left)
    dist_right = np.abs(data - val_right)
    
    # If dist_left is smaller, take val_left, otherwise val_right
    clamped = np.where(dist_left <= dist_right, val_left, val_right)
    
    return clamped

# === change this to your folder ===
FOLDER = "/content/drive/MyDrive/TTC/Data"
OUT_MASTER = os.path.join(FOLDER, "master_all.csv")

def detect_header(path):
    with open(path, "r", errors="ignore") as f:
        for i, line in enumerate(f):
            if "\t" in line:
                toks = line.rstrip("\n").split("\t")
                if {"ET","V","SA","IA","FX","FY","FZ","MZ","SR"}.issubset(set(toks)):
                    return i, toks
    raise RuntimeError("No Round-9 header in: " + path)

def read_round9_run_keep_all(path):
    """Read TTC Round-9 Run file, keep ALL columns, add canonical duplicates."""
    hdr_idx, names = detect_header(path)
    df = pd.read_csv(path, sep="\t", names=names, skiprows=hdr_idx+2, engine="python")
    # drop any trailing-tab anonymous columns
    df = df.loc[:, ~df.columns.str.startswith("Unnamed")]

    # ---- Add canonical duplicates (do NOT drop originals) ----
    # time
    if "ET" in df.columns and "time" not in df.columns:
        df["time"] = pd.to_numeric(df["ET"], errors="coerce")

    # longitudinal slip ratio (kappa)
    if "SR" in df.columns and "KAPPA" not in df.columns:
        df["KAPPA"] = pd.to_numeric(df["SR"], errors="coerce")

    # temperatures → keep TSTI/TSTC/TSTO if present and add TIRE_TEMP (median)
    for tcol in ["TSTI","TSTC","TSTO","RST"]:
        if tcol in df.columns:
            df[tcol] = pd.to_numeric(df[tcol], errors="coerce")
    if all(c in df.columns for c in ["TSTI","TSTC","TSTO"]):
        df["TIRE_TEMP"] = df[["TSTI","TSTC","TSTO"]].median(axis=1)

    # Ensure core numeric columns are numeric (but DO NOT drop any other string cols)
    for c in ["FX","FY","FZ","MX","MY","MZ","SA","IA","V","P"]:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")

    return df

def classify_test_type(df):
    """Heuristic: look at spans of SA and KAPPA in THIS run."""
    sa = pd.to_numeric(df["SA"], errors="coerce").dropna() if "SA" in df else pd.Series(dtype=float)
    kp = pd.to_numeric(df["KAPPA"], errors="coerce").dropna() if "KAPPA" in df else pd.Series(dtype=float)
    sa_span = (sa.max()-sa.min()) if len(sa) else 0.0
    kp_span = (kp.max()-kp.min()) if len(kp) else 0.0
    sa_big = sa_span > np.deg2rad(6)     # ~±6°
    kp_big = kp_span > 0.16              # ~±6%
    if sa_big and not kp_big: return "lateral_pure"
    if kp_big and not sa_big: return "longitudinal_pure"
    if sa_big and kp_big:     return "combined"
    return "unknown"

def summarize_setpoints(df):
    """Run-level medians for convenience (kept as extra columns)."""
    def med(col):
        return float(np.nanmedian(pd.to_numeric(df[col], errors="coerce"))) if col in df else np.nan
    return {
        "FZ_set": med("FZ"),
        "IA_set": med("IA"),
        "V_set":  med("V"),
        "P_set":  med("P"),
        "T_set":  med("TIRE_TEMP") if "TIRE_TEMP" in df else np.nan,
    }

# ------------ build master (keeping ALL columns) ------------
def buildMaster(folder, outMaster, outBlockGuide):
    rows, meta = [], []
    for path in sorted(glob.glob(os.path.join(folder,"*.dat"))):
        run_id = Path(path).stem
        try:
            df = read_round9_run_keep_all(path)
            ttype = classify_test_type(df)
            sp = summarize_setpoints(df)

            # Create a new 'block_id' column
            # It increments by 1 every time the gap in 'ET' from the previous row is > 1.0s

            # attach run metadata (without dropping any original columns)
            df["run_id"] = run_id
            df["test_type"] = ttype
            df["FZ_set"], df["IA_set"], df["V_set"], df["P_set"], df["T_set"] = \
                sp["FZ_set"], sp["IA_set"], sp["V_set"], sp["P_set"], sp["T_set"]

            rows.append(df)
            meta.append({"run_id": run_id, "test_type": ttype, **sp, "rows": len(df.columns)})
            print(f"Added {run_id}: {ttype}, cols={len(df.columns)}, rows={len(df)}")
        except Exception as e:
            print(f"Failed on {run_id}: {e}")

    master = pd.concat(rows, ignore_index=True) if rows else pd.DataFrame()
    master["block_id"] = (master["ET"].diff() > 1).cumsum()
    master["fz_clamped"] = clamp_to_nearest(master, "FZ", fzTestValues)
    rows2 = []
    columns = ["ET", "V", "N", "SA", "IA", "RL", "RE", "P", "FX", "FY", "FZ", "MX", "MZ", "NFX", "NFY", "RST", "TSTI", "TSTC", "TSTO", "AmbTemp", "SR", "time", "KAPPA", "TIRE_TEMP", "run_id", "test_type", "FZ_set", "IA_set", "V_set", "P_set", "T_set", "block_id"]
    for i in range(0, max(master["block_id"])):
        row = master[master["block_id"] == i].iloc[0]
        fz = snapToValues(row["FZ"], fzTestValues)
        inclinationAngle = snapToValues(row["IA"], inclinationAngleTestValues)
        pressure = snapToValues(row["P"], pressureTestValues)
        velocity = snapToValues(row["V"], velocityTestValues)
        row["FZ"] = fz
        row["IA"] = inclinationAngle
        row["P"] = pressure
        row["V"] = velocity
        print(row)
        rows2.append(row)
    blockDataFrame = pd.DataFrame(rows2, columns=columns)
    master.to_csv(outMaster, index=False, sep = "\t")
    blockDataFrame.to_csv(outBlockGuide, index=False, sep = "\t")
    print(f"\nSaved (ALL COLS): {outMaster}  rows={len(master)}, cols={len(master.columns)}")